data <- read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings=("?"))
data$DateTime <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$DateTime)
d12 <- data[(data$Date == as.Date("2007-02-01") | data$Date == as.Date("2007-02-02")),]
png(file="plot4.png")
par(mfcol = c(2,2))
with(d12, plot(DateTime, Global_active_power, type="l", xlab="", ylab="Global Active Power"))
with(d12, {plot(DateTime, Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
lines(DateTime, Sub_metering_1)
lines(DateTime, Sub_metering_2, col="red")
lines(DateTime, Sub_metering_3, col="blue")
legend("topright", bty="n", lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(DateTime, Voltage, type="l", xlab="datetime", lwd=0.5)
plot(DateTime, Global_reactive_power, type="l", xlab="datetime", lwd=0.5)})
# my graphics device is ignoring lwd < 1 so last 2 plots are a little heavy
dev.off()
